Future diledsys
yuriy-tsarenko/java_essential_courses pull request #1
Opened 2021-02-16 16:31 UTC by diledsys

HomeWork_diledsys_Car_task2,3,4

2021-02-16 17:59 UTC, yuriy-tsarenko commented on src/main/java/com/java_essential/diledsys/Classwork/Course/Course.java
> +    public Student[] getStudent() {
getters and setters should be located at one place

2021-02-16 18:06 UTC, yuriy-tsarenko commented on src/main/java/com/java_essential/diledsys/Classwork/Student/Student.java
> +    }//dfgdssdg
delete unnecessary comment please

2021-02-16 18:15 UTC, yuriy-tsarenko commented on src/main/java/com/java_essential/diledsys/homeWork/Computer/Computer.java
> +            ;
delete this symbol

2021-02-16 18:20 UTC, yuriy-tsarenko commented on src/main/java/com/java_essential/diledsys/homeWork/task4_Car/Main.java
> +        //Car zm =new Car("red",180,200,2000);
delete this duplicate object

2021-02-16 18:37 UTC, yuriy-tsarenko commented on src/main/java/com/java_essential/diledsys/myExperiments/Singl/Singl.java
> +public class Singl {
NOTE: constructor with "private" modifier have preferred usage in utility classes,
in this case you should add "final" modifier can to class "Singl".
It means that extending of class "Singl" is forbidden.

2021-02-16 18:43 UTC, yuriy-tsarenko requested changes
Fix code according to my comments

2021-02-16 19:30 UTC, diledsys commented on src/main/java/com/java_essential/diledsys/myExperiments/Singl/Singl.java
> +public class Singl {
дддрол

2021-02-16 19:34 UTC, diledsys commented on src/main/java/com/java_essential/diledsys/myExperiments/Singl/Singl.java
> +public class Singl {
да final тут нужен, это просто тест, я еще делал тест с класом на приоритеты, тоже интиресные моменты , со статичиским блоком и инициализирующим

2021-02-17 11:07 UTC, yuriy-tsarenko approved these changes

2021-02-17 11:09 UTC, merged