Hw01.03.21
yuriy-tsarenko/java_essential_courses pull request #23
Opened 2021-03-01 22:18 UTC by diledsys

2021-03-02 21:08 UTC, ochedenis requested changes

2021-03-02 21:08 UTC, ochedenis commented on src/main/java/com/javae_ssential/diledsys/homeWork/hw010321/worker/Main.java
> +        Scanner reader = new Scanner(System.in);
Split the code with some space between logical blocks.

2021-03-02 21:08 UTC, ochedenis commented on src/main/java/com/javae_ssential/diledsys/homeWork/hw010321/worker/Main.java
> +        }
Main too large. This all "for" block can be a full-fledged method.

2021-03-08 16:26 UTC, yuriy-tsarenko commented
There are no new commits between base branch 'future_diledsys' and head branch 'hw01.03.21'

2021-03-08 16:26 UTC, closed without merging

2021-03-08 16:26 UTC, yuriy-tsarenko commented
There are no new commits between base branch 'future_diledsys' and head branch 'hw01.03.21'