FEATURE-1: first commit
yuriy-tsarenko/java_essential_courses pull request #3
Opened 2021-02-17 07:26 UTC by roninkuma

2021-02-24 22:55 UTC, ochedenis requested changes

2021-02-24 22:55 UTC, ochedenis commented on src/main/java/com/java_essential/SinRoman/lesson_2/Main.java
> +
Clear this empty space.

2021-02-24 22:55 UTC, ochedenis commented on src/main/java/com/java_essential/SinRoman/lesson_2/Main.java
> +
Clear this empty space.

2021-02-24 22:55 UTC, ochedenis commented on src/main/java/com/java_essential/SinRoman/lesson_2/Main.java
> +
Clear this empty space.

2021-02-24 22:55 UTC, ochedenis commented on src/main/java/com/java_essential/SinRoman/lesson_2/Student.java
> +
Clear this empty space.

2021-02-24 22:55 UTC, ochedenis commented on src/main/java/com/java_essential/SinRoman/lesson_2/Student.java
> +
Clear this empty space.

2021-02-25 11:12 UTC, yuriy-tsarenko reviewed
I'm looking forward for your fixing commits Roman)

2021-03-08 16:07 UTC, closed without merging

2021-03-08 16:07 UTC, yuriy-tsarenko commented
Task not completed