Future diledsys
yuriy-tsarenko/java_essential_courses pull request #5
Opened 2021-02-18 22:31 UTC by diledsys

2021-02-19 15:03 UTC, ochedenis requested changes

2021-02-19 15:03 UTC, ochedenis commented on src/main/java/com/java_essential/diledsys/homeWork/ClassRoom/ClassRoom.java
> +
It is bad practice to call methods from a constructor.
Constructor.
Better to use constructor to declare class fields only.
Why empty space?

2021-02-19 15:03 UTC, ochedenis commented on src/main/java/com/java_essential/diledsys/homeWork/ClassRoom/BadPupil.java
> +
Try to avoid useless empty spaces.

2021-02-19 15:03 UTC, ochedenis commented on src/main/java/com/java_essential/diledsys/homeWork/Vehicle/Main.java
> +
Empty space.

2021-02-19 15:03 UTC, ochedenis commented on src/main/java/com/java_essential/diledsys/homeWork/Vehicle/Ship.java
> +    private final String homePort;
Why do not use this field?

2021-02-20 18:42 UTC, ochedenis requested changes

2021-02-20 18:42 UTC, ochedenis commented on src/main/java/com/java_essential/diledsys/homeWork/ClassRoom/ExcelentPupil.java
> +
resting badly ;)
Try to avoid empty spaces.

2021-02-22 10:48 UTC, yuriy-tsarenko requested changes
Fix settings according to my comments and keep notice to NOTEs in future work

2021-02-22 10:48 UTC, yuriy-tsarenko commented on pom.xml
> +    </build>
Change settings according to my variant below

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.java_essential</groupId>
    <artifactId>java_essential_courses</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <java.version>11</java.version>
        <maven-compiler-plugin.version>3.8.0</maven-compiler-plugin.version>
    </properties>
    <dependencies>

    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven-compiler-plugin.version}</version>
                <configuration>
                    <release>${java.version}</release>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
```

2021-02-22 10:48 UTC, yuriy-tsarenko commented on src/main/java/com/java_essential/diledsys/homeWork/ClassRoom/Pupil.java
> +public abstract class Pupil {
NOTE: If you want to describe the behavior of an object only, prefer interface usage

2021-02-25 15:27 UTC, yuriy-tsarenko requested changes

2021-02-25 15:27 UTC, yuriy-tsarenko commented on src/main/java/com/javae_ssential/diledsys/homeWork/Listerator/Main.java
> +        int i=-1;
```suggestion
        int i=-1;
```
change value "-1" to "0"

2021-02-25 15:27 UTC, yuriy-tsarenko commented on src/main/java/com/javae_ssential/diledsys/homeWork/Listerator/Main.java
> +           prime.set(++i,add);
```suggestion
           prime.set(++i,add);
```
delete increment

2021-03-01 11:53 UTC, yuriy-tsarenko approved these changes

2021-03-01 11:53 UTC, merged