hw 8-9
yuriy-tsarenko/java_essential_courses pull request #56
Opened 2021-03-09 21:42 UTC by CherednichenkoNikita

2021-03-10 20:50 UTC, ochedenis approved these changes

2021-03-12 10:29 UTC, yuriy-tsarenko requested changes
Fix bugs according to my comments in similar cases

2021-03-12 10:29 UTC, yuriy-tsarenko commented on src/main/java/com/java_essential/Cherednichenko/homework/lesson_8/task_1/Main.java
> +        });
It's better to shift anonymous class to static nested class

2021-03-12 10:29 UTC, yuriy-tsarenko commented on src/main/java/com/java_essential/Cherednichenko/homework/lesson_9/Device.java
> +                Objects.equals(serialNumber, device.serialNumber);
Avoid bad readable code, simplify to variant bellow
```suggestion
   @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        
        final Device other = (Device) obj;
        
        if (!Objects.equals(this.manufacturer, other.manufacturer)) {
            return false;
        }
        
        if (!Objects.equals(this.price, other.price)) {
            return false;
        }
        if (!Objects.equals(this.serialNumber, other.serialNumber)) {
            return false;
        }
        
        return true;
    }
```

2021-03-12 10:29 UTC, yuriy-tsarenko commented on src/main/java/com/java_essential/Cherednichenko/homework/lesson_9/Device.java
> +    }
You have violated the contract between equals and hashCode.
Change it to variant bellow.
```suggestion
   @Override
    public int hashCode() {
        int hash = 7;
        hash = 73 * hash + Objects.hashCode(manufacturer);
        hash = 73 * hash + Objects.hashCode(price);
        hash = 73 * hash + Objects.hashCode(serialNumber);
        return hash;
    }
```

2021-03-12 10:29 UTC, yuriy-tsarenko commented on src/main/java/com/java_essential/Cherednichenko/homework/lesson_8/task_1/Main.java
> +import java.util.*;
replace this import with single class import

2021-03-12 10:29 UTC, yuriy-tsarenko commented on src/main/java/com/java_essential/Cherednichenko/homework/lesson_8/task_1/Main.java
> +    }
Very big main method body! 
main method it's a access point of your app.

2021-04-02 13:32 UTC, merged