Homework 2,3
yuriy-tsarenko/java_essential_courses pull request #7
Opened 2021-02-22 15:09 UTC by Viktoriia-Zinchenko

2021-02-24 22:59 UTC, ochedenis requested changes

2021-02-24 22:59 UTC, ochedenis commented on src/main/java/com/java_essential/ZinchenkoVika/Classwork/lesson2/Student.java
> +
Clear this empty space.

2021-02-24 22:59 UTC, ochedenis commented on src/main/java/com/java_essential/ZinchenkoVika/Classwork/lesson2/Student.java
> +
CTRL + ALT + L
Add separator between methods.

2021-02-24 22:59 UTC, ochedenis commented on src/main/java/com/java_essential/ZinchenkoVika/Homework/lesson2/Car.java
> +    }
Add separator between constructors.

2021-02-25 16:09 UTC, yuriy-tsarenko requested changes

2021-02-25 16:09 UTC, yuriy-tsarenko commented on src/main/java/Homework/lesson3/Vehicle/Main.java
> +        System.out.println("Plane: price - " + plane.getPrice() + ", speed - " + plane.getSpeed() + ", year - " + plane.getYear() + ", height - " + plane.getHeight() + ", passengers - " + plane.getPa
separate lines that are too long

2021-02-25 16:09 UTC, yuriy-tsarenko commented on src/main/java/Homework/lesson3/Vehicle/Main.java
> +        System.out.println("Ship: price - " + ship.getPrice() + ", speed - " + ship.getSpeed() + ", year - " + ship.getYear() + ", passengers - " + ship.getPassengersShip() + ", port of registration
separate lines that are too long

2021-03-01 10:44 UTC, closed without merging